{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "import tensorflow as tf\n",
    "import os\n",
    "import pickle\n",
    "from IPython.display import clear_output\n",
    "import keras.backend as K\n",
    "from keras.layers import Input, Dense, Reshape, Flatten, Embedding, Dropout\n",
    "# os.environ[\"CUDA_VISIBLE_DEVICES\"] = \"0\"\n",
    "# config = tf.ConfigProto(allow_soft_placement = True)\n",
    "# gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction = 0.5)\n",
    "# config.gpu_options.allow_growth = True\n",
    " \n",
    "# sess0 = tf.InteractiveSession(config = config)\n",
    "\n",
    "# def mutual_info_loss(c, c_given_x):\n",
    "#     \"\"\"The mutual information metric we aim to minimize\"\"\"\n",
    "#     eps = 1e-8\n",
    "#     conditional_entropy = K.mean(- K.sum(K.log(c_given_x + eps) * c, axis=1))\n",
    "#     entropy = K.mean(- K.sum(K.log(c + eps) * c, axis=1))\n",
    "\n",
    "#     return conditional_entropy + entropy\n",
    "'''\n",
    "生成器（generator）\n",
    "首先，建立一個“生成器（generator）”模型，它將一個向量（從潛在空間 - 在訓練期間隨機取樣）轉換為候選影象。\n",
    "GAN通常出現的許多問題之一是generator卡在生成的影象上，看起來像噪聲。一種可能的解決方案是在鑑別器（discriminator）\n",
    "和生成器（generator）上使用dropout。\n",
    "'''\n",
    "import keras\n",
    "from keras import layers\n",
    "import numpy as np\n",
    "\n",
    "num_classes = 52\n",
    "latent_dim = 46\n",
    "height = 92\n",
    "width = 68\n",
    "channels = 3\n",
    "\n",
    "# 兩個input，分別是亂數、類別\n",
    "latent = keras.Input(shape=(latent_dim,))\n",
    "image_class = Input(shape=(1,), dtype='int32')\n",
    "cls = Embedding(num_classes, latent_dim,\n",
    "                embeddings_initializer='glorot_normal')(image_class)\n",
    "\n",
    "generator_input = layers.add([latent, cls])\n",
    "# 首先，將輸入轉換為16x16 128通道的feature map\n",
    "# x = layers.Dense(32 * 46 * 17)(generator_input)\n",
    "# x = layers.LeakyReLU()(x)\n",
    "# # x = layers.Dense(128 * 46 * 17)(x)\n",
    "# # x = layers.LeakyReLU()(x)\n",
    "x = layers.Dense(128 * 46 * 34)(generator_input)\n",
    "x = layers.LeakyReLU()(x)\n",
    "#x = layers.Dropout(0.3)(x)\n",
    "x = layers.Reshape((46, 34, 128))(x)\n",
    "\n",
    "# 然後，添加捲積層\n",
    "# x = layers.Conv2D(256, 5, padding='same')(x)\n",
    "# x = layers.LeakyReLU()(x)\n",
    "\n",
    "# 上取樣至 32 x 32\n",
    "x = layers.Conv2DTranspose(128, 4, strides=2, padding='same')(x)\n",
    "x = layers.LeakyReLU()(x)\n",
    "x = layers.Conv2D(256, 5, padding='same')(x)\n",
    "x = layers.Dropout(0.2)(x)\n",
    "x = layers.LeakyReLU()(x)\n",
    "# 新增更多的卷積層\n",
    "# x = layers.Conv2D(256, 5, padding='same')(x)\n",
    "# x = layers.LeakyReLU()(x)\n",
    "# x = layers.Conv2D(256, 5, padding='same')(x)\n",
    "# x = layers.LeakyReLU()(x)\n",
    "# x = layers.Conv2D(256, 5, padding='same')(x)\n",
    "# x = layers.LeakyReLU()(x)\n",
    "\n",
    "# 生成一個 32x32 1-channel 的feature map\n",
    "x = layers.Conv2D(channels, 16, activation='tanh', padding='same')(x)\n",
    "generator = keras.models.Model([latent, image_class], x)\n",
    "generator.summary()\n",
    "\n",
    "\n",
    "# In[8]:\n",
    "\n",
    "\n",
    "'''\n",
    "discriminator(鑑別器)\n",
    "建立鑑別器模型，它將候選影象（真實的或合成的）作為輸入，並將其分為兩類：“生成的影象”或“來自訓練集的真實影象”。\n",
    "'''\n",
    "discriminator_input = layers.Input(shape=(height, width, channels))\n",
    "x = layers.Conv2D(128, 3)(discriminator_input)\n",
    "x = layers.LeakyReLU()(x)\n",
    "x = layers.Dropout(0.25)(x)\n",
    "x = layers.Dense(128)(x)\n",
    "x = layers.LeakyReLU()(x)\n",
    "x = layers.Conv2D(64, 4, strides=2)(x)\n",
    "x = layers.LeakyReLU()(x)\n",
    "#x = layers.Dropout(0.25)(x)\n",
    "x = layers.Conv2D(32, 4, strides=2)(x)\n",
    "x = layers.LeakyReLU()(x)\n",
    "x = layers.Dense(32)(x)\n",
    "x = layers.LeakyReLU()(x)\n",
    "#x = layers.Dropout(0.25)(x)\n",
    "x = layers.Conv2D(32, 4, strides=2)(x)\n",
    "x = layers.LeakyReLU()(x)\n",
    "x = layers.Flatten()(x)\n",
    "# 重要的技巧（新增一個dropout層）\n",
    "x = layers.Dropout(0,4)(x)\n",
    "\n",
    "# 分類層\n",
    "isFake = layers.Dense(1, activation='sigmoid')(x)\n",
    "classDetac = layers.Dense(num_classes, activation ='softmax')(x)\n",
    "\n",
    "discriminator = keras.models.Model(discriminator_input, [isFake,classDetac])\n",
    "discriminator.summary()\n",
    "\n",
    "# In[11]:\n",
    "# generator = pickle.load(open('generatorClass.p','rb'))\n",
    "# discriminator = pickle.load(open('discriminatorClass.p','rb'))\n",
    "# 為了訓練穩定，在優化器中使用學習率衰減和梯度限幅（按值）。\n",
    "discriminator_optimizer = keras.optimizers.adam(learning_rate=0.0002, beta_1=0.9, beta_2=0.999, amsgrad=False,epsilon=1e-08)\n",
    "discriminator.compile(optimizer=discriminator_optimizer, loss=['binary_crossentropy', 'sparse_categorical_crossentropy'])\n",
    "\n",
    "\n",
    "# In[16]:\n",
    "\n",
    "\n",
    "'''\n",
    "The adversarial network:對抗網路\n",
    "最後，設定GAN，它連結生成器（generator）和鑑別器（discrimitor）。 這是一種模型，經過訓練，\n",
    "將使生成器（generator）朝著提高其愚弄鑑別器（discrimitor）能力的方向移動。 該模型將潛在的空間點轉換為分類決策，\n",
    "“假的”或“真實的”，並且意味著使用始終是“這些是真實影象”的標籤來訓練。 所以訓練`gan`將以一種方式更新\n",
    "“發生器”的權重，使得“鑑別器”在檢視假影象時更可能預測“真實”。 非常重要的是，將鑑別器設定為在訓練\n",
    "期間被凍結（不可訓練）：訓練“gan”時其權重不會更新。 如果在此過程中可以更新鑑別器權重，那麼將訓練鑑別\n",
    "器始終預測“真實”。\n",
    "'''\n",
    "# 將鑑別器（discrimitor）權重設定為不可訓練（僅適用於`gan`模型）\n",
    "\n",
    "discriminator.trainable = False\n",
    "\n",
    "fakeImg = generator([latent, image_class])\n",
    "fake, aux = discriminator(fakeImg)\n",
    "\n",
    "gan = keras.models.Model([latent, image_class], [fake, aux])\n",
    "#losses = [ mutual_info_loss]\n",
    "gan_optimizer = keras.optimizers.adam(learning_rate=0.0002, beta_1=0.9, beta_2=0.999, amsgrad=False,epsilon=1e-08)\n",
    "gan.compile(optimizer=gan_optimizer, loss=['binary_crossentropy', 'sparse_categorical_crossentropy'])\n",
    "gan.summary()\n",
    "\n",
    "# In[19]:\n",
    "\n",
    "\n",
    "# gan = pickle.load(open('gan.p','rb'))\n",
    "'''\n",
    "  開始訓練了。\n",
    "  每個epoch：\n",
    "   *在潛在空間中繪製隨機點（隨機噪聲）。\n",
    "   *使用此隨機噪聲生成帶有“generator”的影象。\n",
    "   *將生成的影象與實際影象混合。\n",
    "   *使用這些混合影象訓練“鑑別器”，使用相應的目標，“真實”（對於真實影象）或“假”（對於生成的影象）。\n",
    "   *在潛在空間中繪製新的隨機點。\n",
    "   *使用這些隨機向量訓練“gan”，目標都是“這些是真實的影象”。 這將更新發生器的權重（僅因為鑑別器在“gan”內被凍結）\n",
    "   以使它們朝向獲得鑑別器以預測所生成影象的“這些是真實影象”，即這訓練發生器欺騙鑑別器。\n",
    " '''\n",
    "import os\n",
    "from keras.preprocessing import image\n",
    "import cv2\n",
    "import numpy as np\n",
    "'''\n",
    "# 匯入CIFAR10資料集\n",
    "(x_train, y_train), (_, _) = keras.datasets.cifar10.load_data()\n",
    "\n",
    "# 從CIFAR10資料集中選擇frog類（class 6）\n",
    "x_train = x_train[y_train.flatten() == 6]\n",
    "\n",
    "# 標準化資料\n",
    "x_train = x_train.reshape(\n",
    "    (x_train.shape[0],) + (height, width, channels)).astype('float32') / 255.\n",
    "'''\n",
    "\n",
    "dirPath = 'C:/Users/User/GAN/SA'\n",
    "SA = [f for f in os.listdir(dirPath) if os.path.isfile(os.path.join(dirPath, f))]\n",
    "x_train = []\n",
    "for img in SA:\n",
    "    imgcv = cv2.imread(dirPath+'/'+img)\n",
    "    imgcv = cv2.cvtColor(imgcv, cv2.COLOR_BGR2RGB)\n",
    "    x_train.append(imgcv)\n",
    "x_train = np.array(x_train)\n",
    "x_train = x_train.reshape(\n",
    "    (x_train.shape[0],) + (height, width, channels)).astype('float32') / 255.\n",
    "\n",
    "lableImg = pickle.load(open('lableImg.p','rb'))\n",
    "\n",
    "iterations = 450000000000\n",
    "batch_size = 40\n",
    "save_dir = '.\\\\gan_image3'\n",
    "\n",
    "start = 0 \n",
    "# 開始訓練迭代\n",
    "for step in range(15200,iterations):\n",
    "    # 在潛在空間中抽樣隨機點\n",
    "    random_latent_vectors = np.random.normal(size=(batch_size, latent_dim))\n",
    "    # 隨機選擇化哪個類別\n",
    "    random_labels = np.random.randint(0, num_classes, batch_size)\n",
    "    # 將隨機抽樣點解碼為假影象\n",
    "    generated_images = generator.predict([random_latent_vectors,random_labels.reshape((-1, 1))])\n",
    "    \n",
    "    # 將假影象與真實影象進行比較\n",
    "    stop = start + batch_size\n",
    "    real_images = x_train[start: stop]\n",
    "    combined_images = np.concatenate([generated_images, real_images])\n",
    "    \n",
    "    # 取真實類別的標籤\n",
    "    \n",
    "    \n",
    "    # 組裝區別真假影象的標籤\n",
    "    labels = np.concatenate([np.ones((batch_size, 1)),\n",
    "                            np.zeros((batch_size, 1))])\n",
    "    # 組裝區別真假類別的標籤\n",
    "    claLabels = lableImg[start: stop]\n",
    "    combined_clsLable = np.concatenate([random_labels, claLabels])\n",
    "    #combined_clsLable = np.concatenate([np.negative(np.ones((batch_size))), claLabels])\n",
    "    \n",
    "    # 重要的技巧，在標籤上新增隨機噪聲\n",
    "    labels += 0.05 * np.random.random(labels.shape)\n",
    "    \n",
    "    # Assign sample weight\n",
    "    disc_sample_weight = [np.ones(2 * (batch_size)),\n",
    "                                  np.concatenate((np.zeros(batch_size) ,\n",
    "                                                  np.ones(batch_size)*3))]\n",
    "    # 訓練鑑別器（discrimitor）\n",
    "    d_loss = discriminator.train_on_batch(combined_images, [labels,combined_clsLable], sample_weight=disc_sample_weight)\n",
    "    \n",
    "\n",
    "    \n",
    "    # 彙集標有“所有真實影象”的標籤\n",
    "    misleading_targets = np.zeros((batch_size, 1))\n",
    "    \n",
    "    # 再做一個新的亂數和標籤\n",
    "    # 在潛在空間中抽樣隨機點\n",
    "    random_latent_vectors = np.random.normal(size=(batch_size, latent_dim))\n",
    "    # 隨機選擇化哪個類別\n",
    "    random_labels = np.random.randint(0, num_classes, batch_size)\n",
    "    \n",
    "    # 訓練生成器（generator）（通過gan模型，鑑別器（discrimitor）權值被凍結）\n",
    "    a_loss = gan.train_on_batch([random_latent_vectors,random_labels.reshape((-1, 1))], [misleading_targets,random_labels])\n",
    "    \n",
    "    start += batch_size\n",
    "    if start > len(x_train) - batch_size:\n",
    "        start = 0\n",
    "    if step % 100 == 0:\n",
    "        # 儲存網路權值\n",
    "        gan.save_weights('gan.h5')\n",
    "        if step % 100 == 0:\n",
    "            print(discriminator.predict(combined_images))\n",
    "        # 輸出metrics\n",
    "        print('discriminator loss at step %s: %s' % (step, d_loss))\n",
    "        print('adversarial loss at step %s: %s' % (step, a_loss))\n",
    "\n",
    "        # 儲存生成的影象\n",
    "        img = image.array_to_img(generated_images[0] * 255., scale=False)\n",
    "        img.save(os.path.join(save_dir, str(step) + '.png'))\n",
    "        \n",
    "        pickle.dump(discriminator,open('discriminatorClass.p','wb'))\n",
    "        pickle.dump(generator,open('generatorClass.p','wb'))\n",
    "        pickle.dump(gan,open('ganClass.p','wb'))\n",
    "        \n",
    "        # 儲存真實影象，以便進行比較\n",
    "#         img = image.array_to_img(real_images[0] * 255., scale=False)\n",
    "#         img.save(os.path.join(save_dir, 'real_SA' + str(step) + '.png'))\n",
    "    if step % 1000 == 0:\n",
    "        clear_output()\n",
    "\n",
    "# In[ ]:\n",
    "\n",
    "\n",
    "# 繪圖\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# 在潛在空間中抽樣隨機點\n",
    "random_latent_vectors = np.random.normal(size=(10, latent_dim))\n",
    "\n",
    "# 將隨機抽樣點解碼為假影象\n",
    "generated_images = generator.predict(random_latent_vectors)\n",
    "\n",
    "for i in range(generated_images.shape[0]):\n",
    "    img = image.array_to_img(generated_images[i] * 255., scale=False)\n",
    "    plt.figure()\n",
    "    plt.imshow(img)\n",
    "    \n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
